services:
  # FastAPI Backend
  - type: web
    name: loud-curator-api
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: SLACK_WEBHOOK_FIGMA_URL
        sync: false
      - key: NEWSDATA_API_KEY
        sync: false
      - key: GROUNDNEWS_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://loud-curator-app.onrender.com 